[workspace]
resolver = "2"
members = [
  "crates/burn_synth_import",
  "crates/burn_flex_gmm",
  "crates/burn_synth",
  "crates/burn_trellis",
  "crates/burn_tripo",
  "crates/bevy_synth",
  "crates/bevy_synth_runtime",
  "crates/bevy_synth_ui",
  "crates/burn_foreground",
  "crates/bevy_file_dialog",
  "crates/bevy_editor_core",
  "crates/bevy_transform_gizmos",
  "crates/burn_synth_mcp",
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
opt-level = 3
panic = "unwind"

[profile.wasm-release]
strip = "symbols"
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"

[patch.crates-io]
cubecl-wgpu = { path = "crates/cubecl-wgpu-patched" }
burn_dino = { path = "crates/vendor/burn_dino_new" }
