[package]
name = "bevy_file_dialog"
version = "0.9.1"
edition = "2021"
description = "File system dialogs for loading and saving files using the Bevy game engine"
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = ["xdg-portal", "wayland"]
# Use XDG Desktop Portal instead of GTK on Linux & BSDs
xdg-portal = ["rfd/xdg-portal"]
gtk3 = ["rfd/gtk3"]
wayland = ["rfd/wayland"]

[dependencies]
rfd = { version = "0.17", default-features = false }
crossbeam-channel = "0.5"
bevy_tasks = { version = "0.17", features = ["multi_threaded"] }
bevy_app = { version = "0.17", default-features = false }
bevy_ecs = { version = "0.17", default-features = false }
bevy_utils = "0.17"
bevy_window = { version = "0.17", default-features = false }
bevy_winit = { version = "0.17" }
bevy_derive = "0.17"
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["DataTransfer", "Document", "DragEvent", "EventTarget", "File", "FileList", "Window"] }

[dev-dependencies]
bevy = { version = "0.17", features = ["multi_threaded"] }
