[package]
name = "burn_3d_synth_bevy"
version = "0.1.0"
edition = "2024"

description = "Bevy app for TripoSG image/text to mesh"
license = "MIT OR Apache-2.0"

[features]
default = ["wgpu"]
wgpu = ["burn-wgpu"]
cuda = ["burn-cuda"]

[dependencies]
bevy = "0.17"
bevy_panorbit_camera = "0.33.0"
bevy_asset = "0.17"
bevy_mesh = "0.17"
bytemuck = "1.25"
clap = { version = "4.5", features = ["derive"] }
burn = { version = "0.19", default-features = false, features = ["ndarray", "std"] }
burn_3d_synth_tripo = { path = "../burn_3d_synth_tripo", features = ["import"] }
burn_3d_synth_bg_removal = { path = "../burn_3d_synth_bg_removal", features = ["import"] }
burn-wgpu = { version = "0.19", optional = true }
burn-cuda = { version = "0.19", optional = true }
futures-lite = "2.6"
half = "2.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
safetensors = "0.6"
