[package]
name = "bevy_synth"
version = "0.2.0"
edition = "2024"

description = "bevy media synthesis plugin"
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = ["wgpu", "triposg"]
triposg = ["bevy_synth_runtime/triposg", "bevy_synth_runtime/shared-runtime", "bevy_synth_ui/triposg"]
trellis = ["bevy_synth_runtime/trellis", "bevy_synth_runtime/shared-runtime", "bevy_synth_ui/trellis"]
wgpu = ["bevy_synth_runtime/wgpu", "bevy_synth_runtime/shared-runtime"]
cuda = ["bevy_synth_runtime/cuda", "bevy_synth_runtime/shared-runtime"]
solari = []
dlss = []
force_disable_dlss = []

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "ae2fcc0353d95e887470f0f6fc8a7e434e5549ce", features = ["http", "https", "webgpu"] }
bevy_mesh = { git = "https://github.com/bevyengine/bevy.git", rev = "ae2fcc0353d95e887470f0f6fc8a7e434e5549ce" }
bevy_picking = { git = "https://github.com/bevyengine/bevy.git", rev = "ae2fcc0353d95e887470f0f6fc8a7e434e5549ce", features = ["mesh_picking"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bevy_synth_runtime = { version = "0.2.0", path = "../bevy_synth_runtime", default-features = false, features = ["shared-runtime"] }
bevy_synth_ui = { version = "0.2.0", path = "../bevy_synth_ui" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = "0.3"
